import './src/commons/tasks/load-addresses'
import './src/mana/tasks/load-mana'
import './src/erc721/tasks/load-erc721'
import './src/marketplace/tasks/load-marketplace'
import './src/bid/tasks/load-bid'
