import '../../commons/tasks/load-addresses'
import '../..//mana/tasks/load-mana'
import '../..//erc721/tasks/load-erc721'
import '../..//marketplace/tasks/load-marketplace'
import '../..//bid/tasks/load-bid'
